---
version: '3'
services:

#
# dynamic dns updater
#
  ddns_client:
    env_file:
      - auth.env
    environment:
      - 'POLL=3600'
      - 'TAILSCALE_NETWORK=tenzin-io.org.github'
      - 'CLOUDFLARE_ZONE=tenzin.io'
    build:
      context: ./build-ddns_client 
